// Token
export const INIT_TOKEN = 'INIT_TOKEN'
export const CLEAR_TOKEN = 'CLEAR_TOKEN'
// 登录模块
export const FETCH_USER = 'FETCH_USER'
// 浏览历史栈
export const ADD_HISTORY_ROUTES = 'ADD_HISTORY_ROUTES'
export const REMOVE_HISTORY_ROUTES = 'REMOVE_HISTORY_ROUTES'
export const CLEAR_HISTORY_ROUTES = 'CLEAR_HISTORY_ROUTES'
export const INIT_HISTORY_ROUTES_STATUS = 'INIT_HISTORY_ROUTES_STATUS'
export const HIGHLIGHT_HISTORY_ROUTES = 'HIGHLIGHT_HISTORY_ROUTES'

/* 会员管理 */
export const ADD_USERS_GROUP = 'ADD_USERS_GROUP'
export const INIT_USERS_GROUP = 'INIT_USERS_GROUP'
